In [19]:
"""

LICENSE MIT
2020
Guillaume Rozier
Website : http://www.covidtracker.fr
Mail : guillaume.rozier@telecomnancy.net

README:
This file contains scripts that download data from data.gouv.fr and then process it to build many graphes.
I'm currently cleaning the code, please ask me if something is not clear enough.

The charts are exported to 'charts/images/france'.
Data is download to/imported from 'data/france'.
Requirements: please see the imports below (use pip3 to install them).

"""

"\n\nLICENSE MIT\n2020\nGuillaume Rozier\nWebsite : http://www.covidtracker.fr\nMail : guillaume.rozier@telecomnancy.net\n\nREADME:\nThis file contains scripts that download data from data.gouv.fr and then process it to build many graphes.\nI'm currently cleaning the code, please ask me if something is not clear enough.\n\nThe charts are exported to 'charts/images/france'.\nData is download to/imported from 'data/france'.\nRequirements: please see the imports below (use pip3 to install them).\n\n"

In [20]:
def nbWithSpaces(nb):
    str_nb = str(int(round(nb)))
    if(nb>100000):
        return str_nb[:3] + " " + str_nb[3:]
    elif(nb>10000):
        return str_nb[:2] + " " + str_nb[2:]
    elif(nb>1000):
        return str_nb[:1] + " " + str_nb[1:]
    else:
        return str_nb

In [21]:
import pandas as pd
PATH = "../../"
import france_data_management as data
import plotly.graph_objects as go
import locale
from datetime import datetime
locale.setlocale(locale.LC_ALL, 'fr_FR.UTF-8')
now = datetime.now()

In [22]:
data.download_data()
df_tests =data.import_data_tests_sexe()
df_tests = df_tests[df_tests.cl_age90 == 0]
df_tests["P_rolling"] = df_tests["P"].rolling(window=7).mean()
df_tests

36it [00:08,  4.10it/s]

,fra,jour,P_f,P_h,P,T_f,T_h,T,cl_age90,pop,P_rolling
10,FR,2020-05-13,537,361,901,23355,16303,39839,0,67114995.0,NaN
21,FR,2020-05-14,562,419,1015,25335,17594,43174,0,67114995.0,NaN
32,FR,2020-05-15,564,446,1044,27496,20446,48380,0,67114995.0,NaN
43,FR,2020-05-16,160,131,292,9220,7342,16662,0,67114995.0,NaN
54,FR,2020-05-17,78,64,142,3448,3168,6650,0,67114995.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4487,FR,2021-06-24,1019,946,1978,148055,139736,290539,0,67114995.0,1873.285714
4498,FR,2021-06-25,1100,1002,2117,181244,169243,353326,0,67114995.0,1806.142857
4509,FR,2021-06-26,688,600,1292,107519,98926,207671,0,67114995.0,1785.285714
4520,FR,2021-06-27,213,203,419,26697,24643,51706,0,67114995.0,1790.857143
4531,FR,2021-06-28,1396,1402,2816,165408,151507,318899,0,67114995.0,1807.142857

In [23]:
data.download_data_variants()
df_variants = data.import_data_variants()
df_variants

,fra,semaine,nb_crib,nb_pos,tx_crib,nb_A0,nb_A1,tx_A1,nb_B0,nb_B1,tx_B1,nb_C0,nb_C1,tx_C1,jour
0,FR,2021-05-31-2021-06-06,18298.0,61188.0,29.9,13158.0,2667.0,16.9,5862.0,23.0,0.4,5528.0,122.0,2.2,2021-06-06
1,FR,2021-06-01-2021-06-07,18136.0,55716.0,32.6,12888.0,2807.0,17.9,6142.0,24.0,0.4,5838.0,164.0,2.7,2021-06-07
2,FR,2021-06-02-2021-06-08,17987.0,51985.0,34.6,12644.0,2941.0,18.9,6407.0,32.0,0.5,6179.0,208.0,3.3,2021-06-08
3,FR,2021-06-03-2021-06-09,17577.0,47751.0,36.8,12212.0,2987.0,19.7,6661.0,36.0,0.5,6394.0,274.0,4.1,2021-06-09
4,FR,2021-06-04-2021-06-10,16763.0,43662.0,38.4,11559.0,2908.0,20.1,6913.0,44.0,0.6,6640.0,304.0,4.4,2021-06-10
5,FR,2021-06-05-2021-06-11,16228.0,40094.0,40.5,11148.0,2869.0,20.5,6975.0,45.0,0.6,6702.0,318.0,4.5,2021-06-11
6,FR,2021-06-06-2021-06-12,15937.0,37808.0,42.2,10962.0,2783.0,20.2,7078.0,43.0,0.6,6785.0,352.0,4.9,2021-06-12
7,FR,2021-06-07-2021-06-13,15808.0,37295.0,42.4,10873.0,2757.0,20.2,7041.0,48.0,0.7,6748.0,357.0,5.0,2021-06-13
8,FR,2021-06-08-2021-06-14,14759.0,32927.0,44.8,10169.0,2522.0,19.9,7377.0,60.0,0.8,7092.0,470.0,6.2,2021-06-14
9,FR,2021-06-09-2021-06-15,13934.0,30168.0,46.2,9595.0,2345.0,19.6,7586.0,60.0,0.8,7264.0,555.0,7.1,2021-06-15
10,FR,2021-06-10-2021-06-16,13230.0,27863.0,47.5,9199.0,2128.0,18.8,7831.0,68.0,0.9,7515.0,597.0,7.4,2021-06-16
11,FR,2021-06-11-2021-06-17,12849.0,26078.0,49.3,8886.0,2099.0,19.1,8114.0,76.0,0.9,7763.0,701.0,8.3,2021-06-17
12,FR,2021-06-12-2021-06-18,12266.0,23971.0,51.2,8441.0,1941.0,18.7,8264.0,79.0,0.9,7819.0,841.0,9.7,2021-06-18
13,FR,2021-06-13-2021-06-19,11805.0,22941.0,51.5,8077.0,1885.0,18.9,8172.0,78.0,0.9,7708.0,875.0,10.2,2021-06-19
14,FR,2021-06-14-2021-06-20,11696.0,22772.0,51.4,8010.0,1860.0,18.8,8154.0,75.0,0.9,7665.0,886.0,10.4,2021-06-20
15,FR,2021-06-15-2021-06-21,10613.0,20894.0,50.8,7207.0,1685.0,18.9,7565.0,75.0,1.0,6964.0,936.0,11.8,2021-06-21
16,FR,2021-06-16-2021-06-22,10065.0,19646.0,51.2,6723.0,1643.0,19.6,7223.0,69.0,0.9,6538.0,980.0,13.0,2021-06-22
17,FR,2021-06-17-2021-06-23,9664.0,18777.0,51.5,6277.0,1676.0,21.1,6922.0,57.0,0.8,6129.0,1074.0,14.9,2021-06-23
18,FR,2021-06-18-2021-06-24,9255.0,17934.0,51.6,5889.0,1695.0,22.3,6640.0,50.0,0.7,5734.0,1170.0,16.9,2021-06-24
19,FR,2021-06-19-2021-06-25,8620.0,17147.0,50.3,5396.0,1636.0,23.3,6266.0,51.0,0.8,5263.0,1247.0,19.2,2021-06-25
20,FR,2021-06-20-2021-06-26,8411.0,16830.0,50.0,5237.0,1599.0,23.4,6154.0,52.0,0.8,5079.0,1315.0,20.6,2021-06-26
21,FR,2021-06-21-2021-06-27,8441.0,16828.0,50.2,5246.0,1623.0,23.6,6200.0,50.0,0.8,5100.0,1336.0,20.8,2021-06-27
22,FR,2021-06-22-2021-06-28,8126.0,16812.0,48.3,5112.0,1554.0,23.3,6127.0,42.0,0.7,4711.0,1635.0,25.8,2021-06-28

In [24]:
df_variants["jour"] = df_variants.semaine.apply(lambda x: x[11:]) 
#df_variants = df_variants[df_variants.cl_age90==0]
df_variants

,fra,semaine,nb_crib,nb_pos,tx_crib,nb_A0,nb_A1,tx_A1,nb_B0,nb_B1,tx_B1,nb_C0,nb_C1,tx_C1,jour
0,FR,2021-05-31-2021-06-06,18298.0,61188.0,29.9,13158.0,2667.0,16.9,5862.0,23.0,0.4,5528.0,122.0,2.2,2021-06-06
1,FR,2021-06-01-2021-06-07,18136.0,55716.0,32.6,12888.0,2807.0,17.9,6142.0,24.0,0.4,5838.0,164.0,2.7,2021-06-07
2,FR,2021-06-02-2021-06-08,17987.0,51985.0,34.6,12644.0,2941.0,18.9,6407.0,32.0,0.5,6179.0,208.0,3.3,2021-06-08
3,FR,2021-06-03-2021-06-09,17577.0,47751.0,36.8,12212.0,2987.0,19.7,6661.0,36.0,0.5,6394.0,274.0,4.1,2021-06-09
4,FR,2021-06-04-2021-06-10,16763.0,43662.0,38.4,11559.0,2908.0,20.1,6913.0,44.0,0.6,6640.0,304.0,4.4,2021-06-10
5,FR,2021-06-05-2021-06-11,16228.0,40094.0,40.5,11148.0,2869.0,20.5,6975.0,45.0,0.6,6702.0,318.0,4.5,2021-06-11
6,FR,2021-06-06-2021-06-12,15937.0,37808.0,42.2,10962.0,2783.0,20.2,7078.0,43.0,0.6,6785.0,352.0,4.9,2021-06-12
7,FR,2021-06-07-2021-06-13,15808.0,37295.0,42.4,10873.0,2757.0,20.2,7041.0,48.0,0.7,6748.0,357.0,5.0,2021-06-13
8,FR,2021-06-08-2021-06-14,14759.0,32927.0,44.8,10169.0,2522.0,19.9,7377.0,60.0,0.8,7092.0,470.0,6.2,2021-06-14
9,FR,2021-06-09-2021-06-15,13934.0,30168.0,46.2,9595.0,2345.0,19.6,7586.0,60.0,0.8,7264.0,555.0,7.1,2021-06-15
10,FR,2021-06-10-2021-06-16,13230.0,27863.0,47.5,9199.0,2128.0,18.8,7831.0,68.0,0.9,7515.0,597.0,7.4,2021-06-16
11,FR,2021-06-11-2021-06-17,12849.0,26078.0,49.3,8886.0,2099.0,19.1,8114.0,76.0,0.9,7763.0,701.0,8.3,2021-06-17
12,FR,2021-06-12-2021-06-18,12266.0,23971.0,51.2,8441.0,1941.0,18.7,8264.0,79.0,0.9,7819.0,841.0,9.7,2021-06-18
13,FR,2021-06-13-2021-06-19,11805.0,22941.0,51.5,8077.0,1885.0,18.9,8172.0,78.0,0.9,7708.0,875.0,10.2,2021-06-19
14,FR,2021-06-14-2021-06-20,11696.0,22772.0,51.4,8010.0,1860.0,18.8,8154.0,75.0,0.9,7665.0,886.0,10.4,2021-06-20
15,FR,2021-06-15-2021-06-21,10613.0,20894.0,50.8,7207.0,1685.0,18.9,7565.0,75.0,1.0,6964.0,936.0,11.8,2021-06-21
16,FR,2021-06-16-2021-06-22,10065.0,19646.0,51.2,6723.0,1643.0,19.6,7223.0,69.0,0.9,6538.0,980.0,13.0,2021-06-22
17,FR,2021-06-17-2021-06-23,9664.0,18777.0,51.5,6277.0,1676.0,21.1,6922.0,57.0,0.8,6129.0,1074.0,14.9,2021-06-23
18,FR,2021-06-18-2021-06-24,9255.0,17934.0,51.6,5889.0,1695.0,22.3,6640.0,50.0,0.7,5734.0,1170.0,16.9,2021-06-24
19,FR,2021-06-19-2021-06-25,8620.0,17147.0,50.3,5396.0,1636.0,23.3,6266.0,51.0,0.8,5263.0,1247.0,19.2,2021-06-25
20,FR,2021-06-20-2021-06-26,8411.0,16830.0,50.0,5237.0,1599.0,23.4,6154.0,52.0,0.8,5079.0,1315.0,20.6,2021-06-26
21,FR,2021-06-21-2021-06-27,8441.0,16828.0,50.2,5246.0,1623.0,23.6,6200.0,50.0,0.8,5100.0,1336.0,20.8,2021-06-27
22,FR,2021-06-22-2021-06-28,8126.0,16812.0,48.3,5112.0,1554.0,23.3,6127.0,42.0,0.7,4711.0,1635.0,25.8,2021-06-28

In [25]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.tx_A1,
        name="% mutation E484K (" + str(df_variants.tx_A1.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.tx_B1,
        name="% mutation E484Q (" + str(df_variants.tx_B1.values[-1]).replace(".", ",") + " %)",
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.tx_C1,
        name="% mutation L452R (" + str(df_variants.tx_C1.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)
y=100 - df_variants.tx_A1 - df_variants.tx_B1 - df_variants.tx_C1
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="% Autres (" + str(y.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)

fig.update_yaxes(ticksuffix="%")

fig.update_layout(
     title={
        'text': "Proportion de variants dans les tests positifs (en %)",
        'y':0.99,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
         'font': {'size': 30}
    },
    annotations = [
                    dict(
                        x=0.5,
                        y=1.1,
                        xref='paper',
                        yref='paper',
                        text='Mis à jour le {}. Données : Santé publique France. Auteur : @guillaumerozier - covidtracker.fr.'.format(now.strftime('%d %B')),
                        showarrow = False
                    )]
)
fig.write_image(PATH+"images/charts/france/{}.jpeg".format("variants_pourcent"), scale=2, width=1000, height=600)

In [26]:
fig = go.Figure()
n_days = len(df_variants)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.tx_A1.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Mutation E484K </b><br>" + str(nbWithSpaces(y[-1])) + " (" + str(df_variants.tx_A1.values[-1]).replace(".", ",") + " %) ",
        showlegend=True,
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.tx_B1.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Mutation E484Q </b><br>" + str(nbWithSpaces(y[-1])) + " (" + str(df_variants.tx_B1.values[-1]).replace(".", ",") + " %) ",
        showlegend=True,
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.tx_C1.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Mutation L452R (dont Delta) </b><br>" + str(nbWithSpaces(y[-1])).replace(".", ",") + " (" + str(df_variants.tx_C1.values[-1]).replace(".", ",") + " %) ",
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * (100 - df_variants.tx_A1.values - df_variants.tx_B1.values - df_variants.tx_C1.values)/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Autres </b><br>" + str(nbWithSpaces(y[-1])).replace(".", ",") + " (" + str(df_variants.tx_C1.values[-1]).replace(".", ",") + " %) ",
        stackgroup='one'
    )
)


fig.update_yaxes(ticksuffix="")

fig.update_layout(
     title={
        'text': "Nombre de variants dans les cas détectés",
        'y':0.99,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
         'font': {'size': 30}
    },
    annotations = [
                    dict(
                        x=0.5,
                        y=1.1,
                        xref='paper',
                        yref='paper',
                        text='Mis à jour : {}. Données : Santé publique France. Auteur : @guillaumerozier - covidtracker.fr.'.format(now.strftime('%d %B')),
                        showarrow = False
                    )]
)
fig.write_image(PATH+"images/charts/france/{}.jpeg".format("variants_nombre"), scale=2, width=1000, height=600)