In [9]:
"""

LICENSE MIT
2020
Guillaume Rozier
Website : http://www.covidtracker.fr
Mail : guillaume.rozier@telecomnancy.net

README:
This file contains scripts that download data from data.gouv.fr and then process it to build many graphes.
I'm currently cleaning the code, please ask me if something is not clear enough.

The charts are exported to 'charts/images/france'.
Data is download to/imported from 'data/france'.
Requirements: please see the imports below (use pip3 to install them).

"""

"\n\nLICENSE MIT\n2020\nGuillaume Rozier\nWebsite : http://www.covidtracker.fr\nMail : guillaume.rozier@telecomnancy.net\n\nREADME:\nThis file contains scripts that download data from data.gouv.fr and then process it to build many graphes.\nI'm currently cleaning the code, please ask me if something is not clear enough.\n\nThe charts are exported to 'charts/images/france'.\nData is download to/imported from 'data/france'.\nRequirements: please see the imports below (use pip3 to install them).\n\n"

In [10]:
def nbWithSpaces(nb):
    str_nb = str(int(round(nb)))
    if(nb>100000):
        return str_nb[:3] + " " + str_nb[3:]
    elif(nb>10000):
        return str_nb[:2] + " " + str_nb[2:]
    elif(nb>1000):
        return str_nb[:1] + " " + str_nb[1:]
    else:
        return str_nb

In [11]:
import pandas as pd
PATH = "../../"
import france_data_management as data
import plotly.graph_objects as go
import locale
from datetime import datetime
locale.setlocale(locale.LC_ALL, 'fr_FR.UTF-8')
now = datetime.now()

In [12]:
data.download_data()
df_tests =data.import_data_tests_sexe()
df_tests = df_tests[df_tests.cl_age90 == 0]
df_tests["P_rolling"] = df_tests["P"].rolling(window=7).mean()
df_tests

36it [00:06,  5.30it/s]

,fra,jour,P_f,P_h,P,T_f,T_h,T,cl_age90,pop,P_rolling
10,FR,2020-05-13,537,361,901,23368,16324,39872,0,67114995.0,NaN
21,FR,2020-05-14,561,418,1013,25327,17616,43188,0,67114995.0,NaN
32,FR,2020-05-15,565,447,1046,27514,20518,48470,0,67114995.0,NaN
43,FR,2020-05-16,160,131,292,9232,7342,16674,0,67114995.0,NaN
54,FR,2020-05-17,78,62,140,3446,3162,6642,0,67114995.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3277,FR,2021-03-06,8039,7457,15558,112933,102862,216380,0,67114995.0,21138.142857
3288,FR,2021-03-07,1846,1691,3538,23737,22366,46139,0,67114995.0,21171.142857
3299,FR,2021-03-08,17576,16060,33795,233287,199305,434360,0,67114995.0,21447.000000
3310,FR,2021-03-09,13954,13003,27138,203425,169493,374659,0,67114995.0,21813.285714
3321,FR,2021-03-10,13870,12679,26711,187075,159010,347342,0,67114995.0,22260.000000

In [13]:
data.download_data_variants()
df_variants = data.import_data_variants()
df_variants

,fra,semaine,cl_age90,Nb_tests_PCR_TA_crible,Prc_tests_PCR_TA_crible,Nb_susp_501Y_V1,Prc_susp_501Y_V1,Nb_susp_501Y_V2_3,Prc_susp_501Y_V2_3,Nb_susp_IND,Prc_susp_IND,Nb_susp_ABS,Prc_susp_ABS,jour
210,FR,2021-02-12-2021-02-18,0,81551,52.1,38098,46.7,3517,4.3,6997,8.6,32939,40.4,2021-02-18
211,FR,2021-02-13-2021-02-19,0,88871,55.3,41417,46.6,4010,4.5,7805,8.8,35639,40.1,2021-02-19
212,FR,2021-02-14-2021-02-20,0,91863,56.3,43113,46.9,4276,4.7,7973,8.7,36501,39.7,2021-02-20
213,FR,2021-02-15-2021-02-21,0,92584,56.6,43582,47.1,4298,4.6,8089,8.7,36615,39.5,2021-02-21
214,FR,2021-02-16-2021-02-22,0,96800,57.4,47634,49.2,4475,4.6,8525,8.8,36166,37.4,2021-02-22
215,FR,2021-02-17-2021-02-23,0,99976,58.1,50889,50.9,4829,4.8,8833,8.8,35425,35.4,2021-02-23
216,FR,2021-02-18-2021-02-24,0,102089,58.6,53820,52.7,5011,4.9,8790,8.6,34468,33.8,2021-02-24
217,FR,2021-02-19-2021-02-25,0,103529,59.1,56192,54.3,5151,5.0,8947,8.6,33239,32.1,2021-02-25
218,FR,2021-02-20-2021-02-26,0,104153,59.4,58221,55.9,5478,5.3,8776,8.4,31678,30.4,2021-02-26
219,FR,2021-02-21-2021-02-27,0,104545,59.5,59168,56.6,5637,5.4,8805,8.4,30935,29.6,2021-02-27
220,FR,2021-02-22-2021-02-28,0,104607,59.5,59337,56.7,5664,5.4,8777,8.4,30829,29.5,2021-02-28
221,FR,2021-02-23-2021-03-01,0,104611,60.0,61662,58.9,5801,5.5,8609,8.2,28539,27.3,2021-03-01
222,FR,2021-02-24-2021-03-02,0,104061,60.0,63070,60.6,5621,5.4,8587,8.3,26783,25.7,2021-03-02
223,FR,2021-02-25-2021-03-03,0,103356,59.7,64186,62.1,5472,5.3,8581,8.3,25117,24.3,2021-03-03
224,FR,2021-02-26-2021-03-04,0,102767,59.6,65295,63.5,5357,5.2,8559,8.3,23556,22.9,2021-03-04
225,FR,2021-02-27-2021-03-05,0,102502,59.5,66528,64.9,5091,5.0,8717,8.5,22166,21.6,2021-03-05
226,FR,2021-02-28-2021-03-06,0,102735,59.3,67529,65.7,4996,4.9,8757,8.5,21453,20.9,2021-03-06
227,FR,2021-03-01-2021-03-07,0,102584,59.2,67661,66.0,4960,4.8,8687,8.5,21276,20.7,2021-03-07
228,FR,2021-03-02-2021-03-08,0,102832,58.9,69447,67.5,4818,4.7,8926,8.7,19641,19.1,2021-03-08
229,FR,2021-03-03-2021-03-09,0,102814,58.5,70319,68.4,4852,4.7,9037,8.8,18606,18.1,2021-03-09
230,FR,2021-03-04-2021-03-10,0,100801,56.8,69758,69.2,4891,4.9,8886,8.8,17266,17.1,2021-03-10

In [14]:
df_variants["jour"] = df_variants.semaine.apply(lambda x: x[11:]) 
df_variants = df_variants[df_variants.cl_age90==0]
df_variants

,fra,semaine,cl_age90,Nb_tests_PCR_TA_crible,Prc_tests_PCR_TA_crible,Nb_susp_501Y_V1,Prc_susp_501Y_V1,Nb_susp_501Y_V2_3,Prc_susp_501Y_V2_3,Nb_susp_IND,Prc_susp_IND,Nb_susp_ABS,Prc_susp_ABS,jour
210,FR,2021-02-12-2021-02-18,0,81551,52.1,38098,46.7,3517,4.3,6997,8.6,32939,40.4,2021-02-18
211,FR,2021-02-13-2021-02-19,0,88871,55.3,41417,46.6,4010,4.5,7805,8.8,35639,40.1,2021-02-19
212,FR,2021-02-14-2021-02-20,0,91863,56.3,43113,46.9,4276,4.7,7973,8.7,36501,39.7,2021-02-20
213,FR,2021-02-15-2021-02-21,0,92584,56.6,43582,47.1,4298,4.6,8089,8.7,36615,39.5,2021-02-21
214,FR,2021-02-16-2021-02-22,0,96800,57.4,47634,49.2,4475,4.6,8525,8.8,36166,37.4,2021-02-22
215,FR,2021-02-17-2021-02-23,0,99976,58.1,50889,50.9,4829,4.8,8833,8.8,35425,35.4,2021-02-23
216,FR,2021-02-18-2021-02-24,0,102089,58.6,53820,52.7,5011,4.9,8790,8.6,34468,33.8,2021-02-24
217,FR,2021-02-19-2021-02-25,0,103529,59.1,56192,54.3,5151,5.0,8947,8.6,33239,32.1,2021-02-25
218,FR,2021-02-20-2021-02-26,0,104153,59.4,58221,55.9,5478,5.3,8776,8.4,31678,30.4,2021-02-26
219,FR,2021-02-21-2021-02-27,0,104545,59.5,59168,56.6,5637,5.4,8805,8.4,30935,29.6,2021-02-27
220,FR,2021-02-22-2021-02-28,0,104607,59.5,59337,56.7,5664,5.4,8777,8.4,30829,29.5,2021-02-28
221,FR,2021-02-23-2021-03-01,0,104611,60.0,61662,58.9,5801,5.5,8609,8.2,28539,27.3,2021-03-01
222,FR,2021-02-24-2021-03-02,0,104061,60.0,63070,60.6,5621,5.4,8587,8.3,26783,25.7,2021-03-02
223,FR,2021-02-25-2021-03-03,0,103356,59.7,64186,62.1,5472,5.3,8581,8.3,25117,24.3,2021-03-03
224,FR,2021-02-26-2021-03-04,0,102767,59.6,65295,63.5,5357,5.2,8559,8.3,23556,22.9,2021-03-04
225,FR,2021-02-27-2021-03-05,0,102502,59.5,66528,64.9,5091,5.0,8717,8.5,22166,21.6,2021-03-05
226,FR,2021-02-28-2021-03-06,0,102735,59.3,67529,65.7,4996,4.9,8757,8.5,21453,20.9,2021-03-06
227,FR,2021-03-01-2021-03-07,0,102584,59.2,67661,66.0,4960,4.8,8687,8.5,21276,20.7,2021-03-07
228,FR,2021-03-02-2021-03-08,0,102832,58.9,69447,67.5,4818,4.7,8926,8.7,19641,19.1,2021-03-08
229,FR,2021-03-03-2021-03-09,0,102814,58.5,70319,68.4,4852,4.7,9037,8.8,18606,18.1,2021-03-09
230,FR,2021-03-04-2021-03-10,0,100801,56.8,69758,69.2,4891,4.9,8886,8.8,17266,17.1,2021-03-10

In [15]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_ABS,
        name="% souche classique (" + str(df_variants.Prc_susp_ABS.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_501Y_V1,
        name="% variant UK (" + str(df_variants.Prc_susp_501Y_V1.values[-1]).replace(".", ",") + " %)",
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_IND,
        name="% variants indéterminés (" + str(df_variants.Prc_susp_IND.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_501Y_V2_3,
        name="% variants SA + BZ (" + str(df_variants.Prc_susp_501Y_V2_3.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)

fig.update_yaxes(ticksuffix="%")

fig.update_layout(
     title={
        'text': "Proportion de variants dans les tests positifs (en %)",
        'y':0.99,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
         'font': {'size': 30}
    },
    annotations = [
                    dict(
                        x=0.5,
                        y=1.1,
                        xref='paper',
                        yref='paper',
                        text='Mis à jour le {}. Données : Santé publique France. Auteur : @guillaumerozier - covidtracker.fr.'.format(now.strftime('%d %B')),
                        showarrow = False
                    )]
)
fig.write_image(PATH+"images/charts/france/{}.jpeg".format("variants_pourcent"), scale=2, width=1000, height=600)

In [16]:
fig = go.Figure()
n_days = len(df_variants)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_501Y_V2_3.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variants SA + BZ </b><br>" + str(nbWithSpaces(y[-1])) + " (" + str(df_variants.Prc_susp_501Y_V2_3.values[-1]).replace(".", ",") + " %) ",
        showlegend=True,
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_IND.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variants indéterminés </b><br>" + str(nbWithSpaces(y[-1])) + " (" + str(df_variants.Prc_susp_IND.values[-1]).replace(".", ",") + " %) ",
        showlegend=True,
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_501Y_V1.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variant UK </b><br>" + str(nbWithSpaces(y[-1])).replace(".", ",") + " (" + str(df_variants.Prc_susp_501Y_V1.values[-1]).replace(".", ",") + " %) ",
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_ABS.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Souche classique </b><br>" + str(nbWithSpaces(y[-1])) + " (" + str(df_variants.Prc_susp_ABS.values[-1]).replace(".", ",") + " %) ",
        showlegend=True,
        stackgroup='one'
    )
)


fig.update_yaxes(ticksuffix="")

fig.update_layout(
     title={
        'text': "Nombre de variants dans les cas détectés",
        'y':0.99,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
         'font': {'size': 30}
    },
    annotations = [
                    dict(
                        x=0.5,
                        y=1.1,
                        xref='paper',
                        yref='paper',
                        text='Mis à jour : {}. Données : Santé publique France. Auteur : @guillaumerozier - covidtracker.fr.'.format(now.strftime('%d %B')),
                        showarrow = False
                    )]
)
fig.write_image(PATH+"images/charts/france/{}.jpeg".format("variants_nombre"), scale=2, width=1000, height=600)